development: &development
  adapter: postgresql
  database: mathaffirm
  username: math_affirm
  password: silly
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: test_mathaffirm

production:
  <<: *development
  database: production_mathaffirm
