development: &development
  adapter: postgresql
  database: oc
  username: postgres
  password: postgres
  host:     localhost
  schema_search_path: public
  min_messages: warning

test:
  <<: *development
  database: test_oc

production:
  <<: *development
  database: production_oc
